name: Build HTML documentation

on:
  [push, pull_request]

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install documentation dependencies
        run: |
          python -m pip install -r doc/requirements.txt

      - name: Install qutip-qtrl from GitHub
        run: |
          python -m pip install -e .[full]
          # Install in editable mode so it doesn't matter if we import from
          # inside the installation directory, otherwise we can get some errors
          # because we're importing from the wrong location.
          python -c 'import qutip_qtrl; print("QuTiP Qtrl Version:      %s" % qutip_qtrl.__version__)'
          python -c 'import qutip; qutip.about()'

      - name: Build documentation
        working-directory: doc
        run: |
          make html SPHINXOPTS="-W --keep-going -T"
          # Above flags are:
          #   -W : turn warnings into errors
          #   --keep-going : do not stop after the first error
          #   -T : display a full traceback if a Python exception occurs

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: qutip_qtrl_html_docs
          path: doc/_build/html/*
          if-no-files-found: error
